package com.currencyconverter.util

object Constants {

        const val CURRENCY_CODE_USD = "USD"
        const val CURRENCY_CODE_EUR = "EUR"
        const val CURRENCY_CODE_CHF = "CHF"
        const val CURRENCY_CODE_HRK = "HRK"
        const val CURRENCY_CODE_MXN = "MXN"
        const val CURRENCY_CODE_ZAR = "ZAR"
        const val CURRENCY_CODE_CNY = "CNY"
        const val CURRENCY_CODE_THB = "THB"
        const val CURRENCY_CODE_AUD = "AUD"
        const val CURRENCY_CODE_ILS = "ILS"
        const val CURRENCY_CODE_KRW = "KRW"
        const val CURRENCY_CODE_JPY = "JPY"
        const val CURRENCY_CODE_PLN = "PLN"
        const val CURRENCY_CODE_GBP = "GBP"
        const val CURRENCY_CODE_IDR = "IDR"
        const val CURRENCY_CODE_HUF = "HUF"
        const val CURRENCY_CODE_PHP = "PHP"
        const val CURRENCY_CODE_TRY = "TRY"
        const val CURRENCY_CODE_RUB = "RUB"
        const val CURRENCY_CODE_HKD = "HKD"
        const val CURRENCY_CODE_ISK = "ISK"
        const val CURRENCY_CODE_DKK = "DKK"
        const val CURRENCY_CODE_CAD = "CAD"
        const val CURRENCY_CODE_MYR = "MYR"
        const val CURRENCY_CODE_BGN = "BGN"
        const val CURRENCY_CODE_NOK = "NOK"
        const val CURRENCY_CODE_RON = "RON"
        const val CURRENCY_CODE_SGD = "SGD"
        const val CURRENCY_CODE_CZK = "CZK"
        const val CURRENCY_CODE_SEK = "SEK"
        const val CURRENCY_CODE_NZD = "NZD"
        const val CURRENCY_CODE_BRL = "BRL"
        const val CURRENCY_CODE_INR = "INR"

}